import type { Metadata } from 'next';
import React from 'react';
import Navigation from '../components/navigation';
import '../styles/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="wrap">
          <div className="is_nav">{children}</div>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
