import type { Metadata } from 'next';
import React from 'react';
import Navigation from '../components/navigation';
import ClientProvider from './ClientProvider'; // 새로 만든 ClientProvider 컴포넌트를 import
import '../styles/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientProvider>
          <div className="wrap">
            <div className="is_nav">{children}</div>
            <Navigation />
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
